<?php
declare(strict_types=1);

use Hyva\Theme\Model\ViewModelRegistry;
use Magento\Framework\View\Element\Template;
use Magento\Framework\Escaper;
use Siteation\StoreInfo\ViewModel\StoreInfo;

/** @var ViewModelRegistry $viewModels */
/** @var Template $block */
/** @var Escaper $escaper */

/** @var StoreInfo $storeInfo */
$storeInfo = $viewModels->require(StoreInfo::class);
?>

<address class="storeinfo not-italic">
    <div itemprop="address" itemscope itemtype="https://schema.org/PostalAddress">
        <?php if ($address1 = $storeInfo->getStreetLine1()): ?>
            <span itemprop="streetAddress">
                <span class="street-address-1"><?= $escaper->escapeHtml($address1); ?></span>
                <?php if ($address2 = $storeInfo->getStreetLine2()): ?>
                    <span class="street-address-2"><?= $escaper->escapeHtml($address2); ?></span>
                <?php endif; ?>
            </span><br>
        <?php endif; ?>
        <?php if ($postcode = $storeInfo->getPostcode()): ?>
            <span class="postcode" itemprop="postalCode"><?= $escaper->escapeHtml($postcode); ?></span>
        <?php endif; ?>
        <?php if ($city = $storeInfo->getCity()): ?>
            <span class="city" itemprop="addressLocality"><?= $escaper->escapeHtml($city); ?></span>
        <?php endif; ?>
    </div>
    <?php if ($phone = $storeInfo->getPhoneNumber()): ?>
        <div>
            <a class="phone" href="tel:<?= $escaper->escapeHtml($phone); ?>"><?= $escaper->escapeHtml($phone); ?></a>
        </div>
    <?php endif; ?>
    <?php if ($email = $storeInfo->getEmail()): ?>
        <div>
            <a class="email" href="mailto:<?= $escaper->escapeHtml($email); ?>"><?= $escaper->escapeHtml($email); ?></a>
        </div>
    <?php endif; ?>
    <?php if ($vat = $storeInfo->getVatNumber()): ?>
        <div class="vat-number"><?= $escaper->escapeHtml($vat); ?></div>
    <?php endif; ?>
</address>
